import React, { useEffect, useState } from 'react'
import { url } from '../../utils/constent';
import { CSVLink } from 'react-csv';
import { FileExcelOutlined } from '@ant-design/icons';

const ExportInExcel = ({ id }) => {
    const [vendor, setVendor] = useState([]);

    const fetchVendor = async () => {
        const res = await fetch(`${url}/api/vendor/details/${id}`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
        const getData = await res.json();
        // console.log(getData);
        setVendor(getData.vendor);
    }

    function exportInCsv() {
        const csvData = [{
            CUSTOMERACCOUNT: "",
            ACCOUNTSTATEMENT: "Always",
            ADDRESSBOOKS: "",
            ADDRESSBUILDINGCOMPLEMENT: "",
            ADDRESSCITY: vendor.companyCity || "",
            ADDRESSCOUNTRYREGIONID: "IND",
            ADDRESSCOUNTRYREGIONISOCODE: "IN",
            ADDRESSCOUNTY: "",
            ADDRESSDESCRIPTION: vendor.companyAddress || "",
            ADDRESSDISTRICTNAME: "",
            ADDRESSLATITUDE: ".000000",
            ADDRESSLOCATIONID: "",
            ADDRESSLOCATIONROLES: "Business;Delivery",
            ADDRESSLONGITUDE: ".000000",
            ADDRESSPOSTBOX: "",
            ADDRESSSTATE: "UP",
            ADDRESSSTREET: vendor.companyAddress || "",
            ADDRESSSTREETNUMBER: "",
            ADDRESSTIMEZONE: "",
            ADDRESSVALIDFROM: "",
            ADDRESSVALIDTO: "",
            ADDRESSZIPCODE: vendor.companyPin || "",
            CALCULATEWITHHOLDINGTAX: "No",
            CENTRALBANKPURPOSECODE: "",
            CENTRALBANKPURPOSENOTES: "",
            CHARGESGROUPID: "",
            COLLECTIONSCONTACTPERSONID: "",
            COMMISSIONCUSTOMERGROUPID: "",
            COMMISSIONSALESGROUPID: "",
            COMPANYCHAIN: "",
            CONTACTPERSONID: "",
            CREDITCARDADDRESSVERIFICATION: "None",
            CREDITCARDADDRESSVERIFICATIONISAUTHORIZATIONVOIDEDONFAILURE: "No",
            CREDITCARDADDRESSVERIFICATIONLEVEL: "Accept",
            CREDITCARDCVC: "None",
            CREDITLIMIT: ".000000",
            CREDITLIMITISMANDATORY: "No",
            CREDITRATING: "",
            CUSTCLASSIFICATIONID: "",
            CUSTOMERGROUPID: vendor.purchaseType || "",
            CUSTOMERREBATEGROUPID: "",
            CUSTOMERTMAGROUPID: "",
            CUSTOMERTYPE: "None",
            DEFAULTDIMENSIONDISPLAYVALUE: "",
            DEFAULTECOMMERCEOPERATOR: "",
            DEFAULTINVENTORYSTATUSID: "",
            DELIVERYADDRESSBUILDINGCOMPLEMENT: "",
            DELIVERYADDRESSCITY: "",
            DELIVERYADDRESSCOUNTRYREGIONID: "",
            DELIVERYADDRESSCOUNTRYREGIONISOCODE: "",
            DELIVERYADDRESSCOUNTY: "",
            DELIVERYADDRESSDESCRIPTION: "",
            "DELIVERYADDRESSDISTRICTNAM+BB1E": "",
            DELIVERYADDRESSLATITUDE: "",
            DELIVERYADDRESSLOCATIONID: "",
            DELIVERYADDRESSLONGITUDE: "",
            DELIVERYADDRESSSTATE: "",
            DELIVERYADDRESSSTREET: "",
            DELIVERYADDRESSSTREETNUMBER: "",
            DELIVERYADDRESSTIMEZONE: "",
            DELIVERYADDRESSVALIDFROM: "",
            DELIVERYADDRESSVALIDTO: "",
            DELIVERYADDRESSZIPCODE: "",
            DELIVERYFREIGHTZONE: "",
            DELIVERYMODE: "",
            DELIVERYREASON: "",
            DELIVERYTERMS: "",
            DESTINATIONCODE: "",
            DISCOUNTPRICEGROUPID: "BR-RUPPAM",
            ELECTRONICLOCATIONID: "",
            EMPLOYEERESPONSIBLENUMBER: "",
            FOREIGNCUSTOMER: "No",
            FULFILLMENTPOLICYNAME: "",
            FULLPRIMARYADDRESS: vendor.companyAddress || "",
            IDENTIFICATIONNUMBER: "",
            INVOICEACCOUNT: "",
            INVOICEADDRESS: "InvoiceAccount",
            INVOICEADDRESSBUILDINGCOMPLEMENT: "",
            INVOICEADDRESSCITY: "",
            INVOICEADDRESSCOUNTRYREGIONID: "",
            INVOICEADDRESSCOUNTRYREGIONISOCODE: "",
            INVOICEADDRESSCOUNTY: "",
            INVOICEADDRESSDESCRIPTION: "",
            INVOICEADDRESSDISTRICTNAME: "",
            INVOICEADDRESSLATITUDE: "",
            INVOICEADDRESSLOCATIONID: "",
            INVOICEADDRESSLONGITUDE: "",
            INVOICEADDRESSSTATE: "",
            INVOICEADDRESSSTREET: "",
            INVOICEADDRESSSTREETNUMBER: "",
            INVOICEADDRESSTIMEZONE: "",
            INVOICEADDRESSVALIDFROM: "",
            INVOICEADDRESSVALIDTO: "",
            INVOICEADDRESSZIPCODE: "",
            ISELECTRONICINVOICE: "No",
            ISEXCLUDEDFROMCOLLECTIONFEECALCULATION: "No",
            ISEXCLUDEDFROMINTERESTCHARGECALCULATION: "No",
            ISEXPRESSBILLOFLADINGACCEPTED: "No",
            ISEXTERNALLYMAINTAINED: "No",
            ISFREIGHTACCRUED: "No",
            ISONETIMECUSTOMER: "No",
            ISORDERNUMBERREFERENCEUSED: "No",
            ISPURCHREQUESTUSED: "No",
            ISSALESTAXINCLUDEDINPRICES: "No",
            ISTRANSACTIONPOSTEDASSHIPMENT: "No",
            ITEMCUSTOMERGROUPID: "",
            KNOWNAS: "",
            LANGUAGEID: "en-IN",
            LINEDISCOUNTCODE: "BR-UPLPAM",
            LINEOFBUSINESSID: "",
            MERCHANTID: "",
            MULTILINEDISCOUNTCODE: "",
            NAMEALIAS: vendor.companyName || "",
            NATUREOFASSESSEE: "Company",
            NUMBERSEQUENCEGROUP: "",
            ONHOLDSTATUS: "No",
            ORDERENTRYDEADLINE: "",
            ORGANIZATIONABCCODE: "None",
            ORGANIZATIONNAME: vendor.companyName || "",
            ORGANIZATIONNUMBER: "",
            ORGANIZATIONNUMBEROFEMPLOYEES: "0",
            ORGANIZATIONPHONETICNAME: "",
            PACKINGDUTYLICENSE: "",
            PACKINGMATERIALFEELICENSENUMBER: "",
            PANNUMBER: "",
            PANREFERENCENUMBER: "",
            PANSTATUS: "NotAvailable",
            PARTYCOUNTRY: "",
            PARTYNUMBER: "",
            PARTYSTATE: "",
            PARTYTYPE: "Organization",
            PAYMENTBANKACCOUNT: "",
            PAYMENTCASHDISCOUNT: "",
            PAYMENTDAY: "",
            PAYMENTMETHOD: "",
            PAYMENTSCHEDULE: "",
            PAYMENTSPECIFICATION: "",
            PAYMENTTERMSBASEDAYS: "0",
            PAYMENTUSECASHDISCOUNT: "Normal",
            PERSONANNIVERSARYDAY: "",
            PERSONANNIVERSARYMONTH: "",
            PERSONANNIVERSARYYEAR: "",
            PERSONCHILDRENNAMES: "",
            PERSONFIRSTNAME: "",
            PERSONGENDER: "",
            PERSONHOBBIES: "",
            PERSONINITIALS: "",
            PERSONLASTNAME: "",
            PERSONLASTNAMEPREFIX: "",
            PERSONMARITALSTATUS: "",
            PERSONMIDDLENAME: "",
            PERSONPHONETICFIRSTNAME: "",
            PERSONPHONETICLASTNAME: "",
            PERSONPHONETICMIDDLENAME: "",
            PERSONPROFESSIONALSUFFIX: "",
            PERSONPROFESSIONALTITLE: "",
            PREFERENTIALCUSTOMER: "No",
            PRIMARYCONTACTEMAIL: "",
            PRIMARYCONTACTEMAILDESCRIPTION: "",
            PRIMARYCONTACTEMAILISIM: "",
            PRIMARYCONTACTEMAILPURPOSE: "",
            PRIMARYCONTACTFACEBOOK: "",
            PRIMARYCONTACTFACEBOOKDESCRIPTION: "",
            PRIMARYCONTACTFACEBOOKPURPOSE: "",
            PRIMARYCONTACTFAX: "",
            PRIMARYCONTACTFAXDESCRIPTION: "",
            PRIMARYCONTACTFAXEXTENSION: "",
            PRIMARYCONTACTFAXPURPOSE: "",
            PRIMARYCONTACTLINKEDIN: "",
            PRIMARYCONTACTLINKEDINDESCRIPTION: "",
            PRIMARYCONTACTLINKEDINPURPOSE: "",
            PRIMARYCONTACTPHONE: vendor.companyNumber || "",
            PRIMARYCONTACTPHONEDESCRIPTION: "",
            PRIMARYCONTACTPHONEEXTENSION: "",
            PRIMARYCONTACTPHONEISMOBILE: "No",
            PRIMARYCONTACTPHONEPURPOSE: "Business",
            PRIMARYCONTACTTELEX: "",
            PRIMARYCONTACTTELEXDESCRIPTION: "",
            PRIMARYCONTACTTELEXPURPOSE: "",
            PRIMARYCONTACTTWITTER: "",
            PRIMARYCONTACTTWITTERDESCRIPTION: "",
            PRIMARYCONTACTTWITTERPURPOSE: "",
            PRIMARYCONTACTURL: "",
            PRIMARYCONTACTURLDESCRIPTION: "",
            PRIMARYCONTACTURLPURPOSE: "",
            RECEIPTCALENDAR: "",
            RECEIPTOPTION: "RetailEx3",
            SALESACCOUNTNUMBER: "",
            SALESCURRENCYCODE: "INR",
            SALESDISTRICT: "",
            SALESMEMO: "",
            SALESORDERPOOLID: "",
            SALESSEGMENTID: "",
            SALESSUBSEGMENTID: "",
            SITEID: "",
            STATISTICSGROUPID: "",
            SUPPLEMENTARYITEMGROUPID: "",
            TAXEXEMPTNUMBER: "",
            TCSGROUP: "",
            TDSGROUP: "",
            VENDORACCOUNT: "",
            WAREHOUSEISASNGENERATED: "No",
            WAREHOUSEISENTIRESHIPMENTFILLED: "No",
            WRITEOFFREASON: "",
        }];

        return csvData;
    }

    useEffect(() => {
        fetchVendor();
    }, [])
    return (
        <>
            <CSVLink
                filename={"vendor_details.csv"}
                data={exportInCsv()}
                style={{ textDecoration: 'none', color: '#08979C', fontWeight: '600' }}
            >
                <FileExcelOutlined style={{ fontSize: '12px', marginBottom: '4px', marginRight: '4px' }} /> Save as Excel
            </CSVLink>
        </>
    )
}

export default ExportInExcel